#!/bin/bash -l
#PBS -l walltime=10:00:00
#PBS -l mem=8gb
#PBS -m abe
#PBS -M gbonaert@ulb.ac.be
#PBS -l nodes=1:ppn=8

module purge
module load scikit-learn/0.19.1-foss-2017b-Python-3.6.3
module load scikit-image/0.13.1-foss-2017b-Python-3.6.3
module load Keras/2.1.3-foss-2017b-Python-3.6.3

cd $PBS_O_WORKDIR
echo submit directory: $PWD
echo jobid: $PBS_JOBID
echo hostname: $HOSTNAME
date
echo --- Start Job ---
python optimizer.py
#python main.py
echo ---- End Job ----
date

